jenkins_plugins:
  - build-timeout
  - build-token-root
  - branch-api
  - credentials
  - checks-api
  - echarts-api
  - disable-github-multibranch-status
  - git
  - git-client
  - github
  - github-api
  - github-client
  - github-checks
  - htmlpublisher
  - junit
  - matrix-auth
  - maven-plugin
  - pipeline
  - pipeline-groovy
  - pipeline-maven
  - pipeline-model-definition
  - pipeline-stage-step
  - pipeline-stage-view
  - scm-api
  - ssh-credentials
  - ssh-slaves
  - sshd
  - warnings-ng
  - workflow-api
  - workspace-cleanup